export const parishData = {
  name: "Paróquia Nossa Senhora do Carmo - Paraopeba",
  heroTitle: "Paróquia Nossa Senhora do Carmo - Paraopeba",
  heroText:
    "Informações da paróquia, secretaria, clero e comunidades da Diocese de Sete Lagoas.",
  celebrationsNote: "Confira nossos principais horários ativos.",
  communicado: "📢 Atenção: Os horários das missas podem sofrer alterações em datas festivas e feriados. Acompanhe nossas redes sociais para confirmações.",
  massTimes: [
    { id: "m1", day: "1° Sexta", time: "19:30", location: "Matriz" },
    { id: "m2", day: "Sábado", time: "19:30", location: "Matriz" },
    { id: "m3", day: "Domingo", time: "07:30 e 19:30", location: "Matriz" },
    { id: "m4", day: "3° Domingo", time: "11:00", location: "Igreja Bom Jesus - Embiriçu" },
    { id: "m5", day: "1° e 3° Quarta do mês", time: "19:30", location: "Igreja Divino Espírito Santo" },
    { id: "m6", day: "4° Sábado", time: "16:00", location: "Igreja Jesus Misericordioso - Aguada" },
    { id: "m7", day: "3° quarta do mês", time: "18:00", location: "Igreja Nossa Senhora Aparecida - Canabrava" },
    { id: "m8", day: "1° Sábado do mês", time: "07:00", location: "Igreja Nossa Senhora do Rosário" },
    { id: "m9", day: "1° e 3° Quinta do mês", time: "06:00", location: "Igreja Nossa Senhora do Rosário" },
    { id: "m10", day: "1° Quinta do Mês", time: "19:30", location: "Igreja Nossa Senhora do Rosário - Pontinha" },
    { id: "m11", day: "Sábado", time: "18:00", location: "Capela Sagrado Coração de Jesus" },
    { id: "m12", day: "3° e 4° Quarta do mês", time: "19:30", location: "Igreja Santa Catarina de Sena" },
    { id: "m13", day: "5° domingo", time: "11:00", location: "Igreja Santa Maria" },
    { id: "m14", day: "Sexta", time: "19:30", location: "Igreja São Benedito" },
    { id: "m15", day: "3° Sexta", time: "19:30", location: "Igreja São Geraldo - Picada" },
    { id: "m16", day: "3° domingo", time: "11:00", location: "Igreja São José - Caboclo", mapLink: "https://maps.app.goo.gl/LPNaarR65rjNC3pZ8" },
    { id: "m17", day: "Dia 28", time: "19:30", location: "Igreja São Judas Tadeu" },
    { id: "m18", day: "Domingo", time: "09:00", location: "Igreja São Judas Tadeu" },
    { id: "m19", day: "2° Domingo do mês", time: "11:00", location: "Igreja Nossa Senhora das Dores - Retiro" },
    { id: "m20", day: "Quarta", time: "06:00", location: "Igreja Nossa Senhora da Piedade" },
    { id: "m21", day: "Domingo", time: "18:00", location: "Igreja Nossa Senhora da Piedade" },
    { id: "m22", day: "2° Sábado", time: "16:00", location: "Igreja São Pedro" },
  ],
  forania: "Nossa Senhora da Abadia",
  foundedYear: "1840",
  officeHours: "Segunda a Sexta: 08h às 12h e 13h às 17h",
  phone: "(31) 3714-1018",
  email: "paroquiaparaopeba@diocesedesetelagoas.com.br",
  secretary: "Maria Clara Gonçalves",
  address: "Praça Caetano Mascarenhas, 480, Centro",
  zipCode: "35774-000",
  clergy: [
    "Rafael Lucas Bastos Ribeiro (Pe.) - Administrador",
    "Roberto Vicente Leite (Vigário)",
  ],
  communitiesShort:
    "Comunidades: Matriz, Bom Jesus, Divino Espírito Santo, Jesus Misericordioso, N. Sra. Aparecida, N. Sra. do Rosário, Sagrado Coração, Santa Catarina, Santa Maria, São Benedito, São Geraldo, São José, São Judas Tadeu, N. Sra. das Dores, N. Sra. da Piedade e Igreja São Pedro.",
  notices: [
    "Acompanhe as celebrações e comunicados pela página oficial.",
    "Horários de missas podem sofrer ajustes em datas especiais.",
  ],
  specialEvents: [
    // Para adicionar o link do Google Maps de cada festa, preencha o campo mapLink: "URL_AQUI"
    { startMonth: 0, startDay: 22, endMonth: 0, endDay: 25, title: 'Festa em honra a São Sebastião "Soldado de Cristo, defensor da unidade"', mapLink: "" },
    { startMonth: 2, startDay: 19, endMonth: 2, endDay: 19, title: "Solenidade em honra a São José", location: "Comunidade São José do Caboclo", mapLink: "" },
    { startMonth: 3, startDay: 9, endMonth: 3, endDay: 12, title: "Festa em honra a Jesus Misericordioso", location: "Comunidade da Aguada", mapLink: "" },
    { startMonth: 3, startDay: 17, endMonth: 3, endDay: 18, title: "ECC 1ª etapa", mapLink: "" },
    { startMonth: 3, startDay: 27, endMonth: 3, endDay: 29, title: "Festa em honra a Santa Catarina de Sena", location: "Comunidade Santa Catarina de Sena", mapLink: "" },
    { startMonth: 4, startDay: 1, endMonth: 4, endDay: 3, title: "Festa em honra a São José", location: "Comunidade do Caboclo", mapLink: "https://maps.app.goo.gl/yFs2UpNARqY7DX1P7" },
    { startMonth: 4, startDay: 1, endMonth: 4, endDay: 3, title: "Festa em honra a São Vicente", location: "SSVP", mapLink: "" },
    { startMonth: 4, startDay: 21, endMonth: 4, endDay: 24, title: "Festa em honra ao Divino Espírito Santo", location: "Associação cultural de Nossa Senhora do Rosário do Retiro", mapLink: "" },
    { startMonth: 4, startDay: 22, endMonth: 4, endDay: 24, title: "1º EAC", location: "Nossa Senhora do Carmo", mapLink: "" },
    { startMonth: 5, startDay: 1, endMonth: 5, endDay: 4, title: "Tríduo Eucarístico e Solenidade do Santíssimo Corpo e Sangue", location: "Comunidade Paroquial. Atenção para a confecção dos tapetes.", mapLink: "" },
    { startMonth: 5, startDay: 9, endMonth: 5, endDay: 12, title: "Festa em honra ao Sagrado Coração de Jesus", location: "Comunidade Sagrado Coração de Jesus", mapLink: "" },
    { startMonth: 5, startDay: 25, endMonth: 5, endDay: 28, title: "Festa em honra a São Pedro", location: "Comunidade do Mocambo", mapLink: "" },
    { startMonth: 6, startDay: 5, endMonth: 6, endDay: 16, title: "Novenário em preparação para a Festa da Padroeira Nossa Senhora do Carmo", location: "Comunidade paroquial", mapLink: "" },
    { startMonth: 6, startDay: 6, endMonth: 6, endDay: 6, title: "186ª FESTA EM HONRA A NOSSA SENHORA DO CARMO - 19h30 Missa de envio das equipes | 20h30 Show com Marcone e seus teclados", location: "Comunidade paroquial", mapLink: "" },
    { startMonth: 6, startDay: 23, endMonth: 6, endDay: 26, title: "Festa em honra a São Geraldo", location: "Picada - Associação local", mapLink: "" },
    { startMonth: 6, startDay: 31, endMonth: 7, endDay: 2, title: "Festa em honra a Nossa Senhora do Rosário", location: "Comunidade da Pontinha", mapLink: "" },
    { startMonth: 6, startDay: 31, endMonth: 7, endDay: 2, title: "Festa em honra a Nossa Senhora das Dores", location: "Comunidade do Retiro", mapLink: "" },
    { startMonth: 7, startDay: 1, endMonth: 7, endDay: 4, title: "Tríduo Vocacional - Dia do padre", location: "RESPONSÁVEIS: Movimento Serra, Apostolado da Oração, Mães que oram pelos filhos e terço dos homens.", mapLink: "" },
    { startMonth: 7, startDay: 17, endMonth: 7, endDay: 23, title: "Festa em honra a Nossa Senhora do Rosário", location: "Comunidade Paroquial", mapLink: "" },
    { startMonth: 7, startDay: 27, endMonth: 7, endDay: 30, title: "Festa em honra a Santa Maria, Mãe de Deus", mapLink: "" },
    { startMonth: 8, startDay: 10, endMonth: 8, endDay: 13, title: "Festa em honra ao Senhor Bom Jesus", location: "Comunidade do Embiruçu", mapLink: "" },
    { startMonth: 8, startDay: 12, endMonth: 8, endDay: 15, title: "Festa em honra a Nossa Senhora da Piedade", location: "Comunidade Nossa Senhora da Piedade", mapLink: "" },
    { startMonth: 9, startDay: 2, endMonth: 9, endDay: 5, title: "Festa em honra a São Benedito, O Mouro", location: "Comunidade São Benedito", mapLink: "" },
    { startMonth: 9, startDay: 9, endMonth: 9, endDay: 12, title: "Festa em honra a Nossa Senhora Aparecida", location: "Comunidade do Canabrava", mapLink: "" },
    { startMonth: 9, startDay: 25, endMonth: 9, endDay: 28, title: "Festa em honra a São Judas Tadeu", location: "Comunidade São Judas", mapLink: "" },
    { startMonth: 10, startDay: 19, endMonth: 10, endDay: 22, title: "Festa em honra a Jesus das Santas Chagas", location: "Comunidade Jesus das Santas Chagas - CRISTO REI, DIA DO LEIGO.", mapLink: "" },
  ],
  carmoFestivalSchedule: [
    { day: "05 de julho", time: "07h30", event: "Caminhada ecológica, corrida de 5km, corrida dos 100m, aulas de Cross, Zumba e muito mais", location: "Praça de Esportes da Padroeira" },
    { day: "05 de julho", time: "11h00", event: "Almoço no espaço social da Igreja Matriz e CUMBUCÃO", location: "Espaço Social da Matriz" },
    { day: "05 de julho", time: "11h00", event: "Show com Banda Zapy", location: "Matriz", isShow: true },
    { day: "05 de julho", time: "20h30", event: "Show com Pancada Bruta", location: "Matriz", isShow: true },
    { day: "06 de julho", time: "19h30", event: "Missa de envio das equipes de serviços dos festejos da padroeira", location: "Matriz" },
    { day: "06 de julho", time: "20h30", event: "Show com Marcone e seus teclados", location: "Matriz", isShow: true },
    { day: "07 de julho", time: "06h00", event: "Repique de sinos – É o anúncio do início da novena!", location: "Matriz" },
    { day: "07 de julho", time: "18h00", event: "Saída da Bandeira de Nossa Senhora do Carmo da casa do sr. Edival e família, em direção à Matriz", location: "Matriz" },
    { day: "07 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Nossa Senhora da Piedade e Nossa Senhora Aparecida do Canabrava", schools: "C.E. Castelinho Encantado, CEIM Ana Maria Moreira, CEIM Elza Moreira Lopes, E.M. Recanto Feliz, E.M. Sabino de Paula Freitas" },
    { day: "07 de julho", time: "20h30", event: "Show com Armando Lopes e Eduardo – Participação Pe. Gilson", location: "Matriz", isShow: true },
    { day: "08 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Santa Catarina de Sena e Jesus Misericordioso da Aguada", schools: "E.E. Agnaldo Edmundo Silva, E.E. Conselheiro Afonso Pena, E.E. Joaquina Cândida Moreira, E.E. Padre Augusto Horta, Colégio Nossa Senhora do Carmo" },
    { day: "08 de julho", time: "20h30", event: "Show com Japão do Forró", location: "Matriz", isShow: true },
    { day: "09 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Nossa Senhora das Dores do Retiro e São Judas Tadeu", schools: "E.M. José Lucas de Figueiredo, E.M. Dr. Teófilo Nascimento e E.M. Américo Vaz da Silva" },
    { day: "09 de julho", time: "20h30", event: "Show com Túlio e Willian", location: "Matriz", isShow: true },
    { day: "10 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Nossa Senhora do Rosário e São Geraldo da Picada" },
    { day: "10 de julho", time: "20h30", event: "Show com Banda Amor de Forró (A volta da Banda Amor de Forró)", location: "Matriz", isShow: true },
    { day: "11 de julho", time: "15h00", event: "Missa com os enfermos da comunidade", location: "Matriz" },
    { day: "11 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Sagrado Coração de Jesus e São José do Caboclo" },
    { day: "11 de julho", time: "20h30", event: "Show com Banda Tarq", location: "Matriz", isShow: true },
    { day: "12 de julho", time: "08h00", event: "Encontro de carros antigos na praça da Matriz", location: "Matriz" },
    { day: "12 de julho", time: "11h00", event: "Almoço no espaço social da Igreja Matriz", location: "Matriz" },
    { day: "12 de julho", time: "11h00", event: "Show com Banda K-22", location: "Matriz", isShow: true },
    { day: "12 de julho", time: "14h00", event: "Desfile de príncipes e princesas no espaço social", location: "Matriz" },
    { day: "12 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Senhor Bom Jesus do Embiruçu e São Pedro do Mocambo" },
    { day: "12 de julho", time: "20h30", event: "Show com Pura Malandragem", location: "Matriz", isShow: true },
    { day: "13 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "São Benedito e Nossa Senhora do Rosário da Pontinha", details: "Após a Missa: NOITE PREMIADA!" },
    { day: "13 de julho", time: "20h30", event: "Show com Rafaela Pontes", location: "Matriz", isShow: true },
    { day: "14 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", communities: "Nossa Senhora da Piedade e Divino Espírito Santo" },
    { day: "14 de julho", time: "20h30", event: "Show com Parceiros do Samba 7", location: "Matriz", isShow: true },
    { day: "15 de julho", time: "19h00", event: "Bênção do Santíssimo Sacramento e em seguida a Santa Missa", location: "Matriz", details: "Participação da comunidade da Matriz." },
    { day: "15 de julho", time: "20h30", event: "Show com Zé Henrique & Adriano", location: "Matriz", isShow: true },
    { day: "16 de julho", time: "06h00", event: "Repique de sinos e recitação do Ofício de Nossa Senhora", location: "Matriz", details: "🎉 DIA DA AUGUSTA PADROEIRA — NOSSA SENHORA DO CARMO" },
    { day: "16 de julho", time: "12h00", event: "Rito da Imposição do Santo Escapulário", location: "Matriz" },
    { day: "16 de julho", time: "12h30", event: "Almoço no espaço social da Matriz", location: "Matriz" },
    { day: "16 de julho", time: "12h30", event: "Show com Fernando Augusto", location: "Matriz", isShow: true },
    { day: "16 de julho", time: "16h00", event: "Solene Celebração Eucarística seguida de procissão", location: "Matriz" },
    { day: "16 de julho", time: "19h00", event: "Show com Banda Brasil 70 Show", location: "Matriz", isShow: true },
  ],
  links: {
    diocesePage:
      "https://diocesedesetelagoas.com.br/paroquias/paroquia-nossa-senhora-do-carmo-paraopeba/",
    instagramProfile: "https://www.instagram.com/paroquiansra.docarmo/",
    instagramPost: "https://www.instagram.com/reel/DaAkIeRBR7g/",
    phoneHref: "tel:+553137141018",
    whatsapp: "https://wa.me/553137141018",
    mapEmbed:
      "https://www.google.com/maps?q=Pra%C3%A7a%20Caetano%20Mascarenhas%2C%20480%2C%20Paraopeba&output=embed",
  },
  pix: {
    key: "escadariamatriz@gmail.com",
    city: "PARAOPEBA",
  },
};
